create table tb_posts (id bigint generated by default as identity, content varchar(500) not null, date timestamp, title varchar(100) not null, theme_id bigint, user_id bigint, primary key (id));
create table tb_themes (id bigint generated by default as identity, name varchar(200) not null, primary key (id));
create table tb_user (id bigint generated by default as identity, hashcode varchar(255) not null, name varchar(100) not null, user varchar(100) not null, primary key (id));
alter table tb_posts add constraint FKdggnipt28x3mski4r9x1silkq foreign key (theme_id) references tb_themes;
alter table tb_posts add constraint FKio3tgr81kj3ejk08bqogu0frr foreign key (user_id) references tb_user;
