create table tb_posts (id int8 generated by default as identity, content varchar(500) not null, date timestamp, title varchar(100) not null, theme_id int8, primary key (id));
create table tb_themes (id int8 generated by default as identity, description varchar(200) not null, primary key (id));
alter table if exists tb_posts add constraint FKdggnipt28x3mski4r9x1silkq foreign key (theme_id) references tb_themes;
